In [1]:
company_detail_list = [
    {
        'name': 'Company 1',
        'domain': 'Retail',
        'country': 'United States'
    },
    {
        'name': 'Company 2',
        'domain': 'Technology',
        'country': 'United Kingdom'
    },
    {
        'name': 'Company 3',
        'domain': 'Healthcare',
        'country': 'United States'
    }
]

# Mendapatkan daftar semua nama perusahaan dan mengurutkannya secara terbalik
sorted_companies = sorted(
    [{'name': company['name']} for company in company_detail_list],
    key=lambda x: x['name'],
    reverse=True
)

# Menampilkan hasil
print(sorted_companies)

[{'name': 'Company 3'}, {'name': 'Company 2'}, {'name': 'Company 1'}]

In [2]:
company_detail_list = [
    {
        'name': 'Company 1',
        'domain': 'Retail',
        'country': 'United States'
    },
    {
        'name': 'Company 2',
        'domain': 'Technology',
        'country': 'United Kingdom'
    },
    {
        'name': 'Company 3',
        'domain': 'Healthcare',
        'country': 'United States'
    }
]

# Loop untuk mencetak informasi setiap perusahaan
for company in company_detail_list:
    print(f"{company['name']}: {company['domain']} ({company['country']})")

Company 1: Retail (United States)
Company 2: Technology (United Kingdom)
Company 3: Healthcare (United States)

In [3]:
company_detail_list = [
    {
        'name': 'Company 1',
        'domain': 'Retail',
        'country': 'United States'
    },
    {
        'name': 'Company 2',
        'domain': 'Technology',
        'country': 'United Kingdom'
    },
    {
        'name': 'Company 3',
        'domain': 'Healthcare',
        'country': 'United States'
    }
]

employee_detail_list = [
    {
        'name': 'EMP-0001',
        'first_name': 'John',
        'last_name': 'Doe',
        'full_name': 'John Doe',
        'company': 'Company 1',
        'nationality': 'Australia'
    },
    {
        'name': 'EMP-0002',
        'first_name': 'Tom',
        'last_name': 'Smith',
        'full_name': 'Tom Smith',
        'company': 'Company 2',
        'nationality': 'United States'
    },
    {
        'name': 'EMP-0003',
        'first_name': 'Andrew',
        'last_name': 'Sebastian',
        'full_name': 'Andrew Sebastian',
        'company': 'Company 3',
        'nationality': 'United States'
    },
    {
        'name': 'EMP-0005',
        'first_name': 'Ying Han',
        'last_name': 'Tan',
        'full_name': 'Ying Han Tan',
        'company': 'Company 1',
        'nationality': 'Australia'
    },
    {
        'name': 'EMP-0015',
        'first_name': 'Kenneth',
        'last_name': 'Ng',
        'full_name': 'Kenneth Ng',
        'company': 'Company 3',
        'nationality': 'United States'
    },
    {
        'name': 'EMP-0018',
        'first_name': 'Rubby',
        'last_name': 'Lee',
        'full_name': 'Rubby Lee',
        'company': 'Company 2',
        'nationality': 'Hong Kong'
    },
    {
        'name': 'EMP-0017',
        'first_name': 'Robert',
        'last_name': 'White',
        'full_name': 'Robert White',
        'company': 'Company 1',
        'nationality': 'United Kingdom'
    }
]

# Membuat mapping antara nama perusahaan dan domainnya
company_domain_map = {company['name']: company['domain'] for company in company_detail_list}

# Mengelompokkan karyawan berdasarkan domain perusahaan
employees_by_domain = {}
for employee in employee_detail_list:
    domain = company_domain_map[employee['company']]
    if domain not in employees_by_domain:
        employees_by_domain[domain] = []
    employees_by_domain[domain].append(employee['full_name'])

# Menampilkan hasil
print(employees_by_domain)

{'Retail': ['John Doe', 'Ying Han Tan', 'Robert White'], 'Technology': ['Tom Smith', 'Rubby Lee'], 'Healthcare': ['Andrew Sebastian', 'Kenneth Ng']}

In [4]:
company_detail_list = [
    {
        'name': 'Company 1',
        'domain': 'Retail',
        'country': 'United States'
    },
    {
        'name': 'Company 2',
        'domain': 'Technology',
        'country': 'United Kingdom'
    },
    {
        'name': 'Company 3',
        'domain': 'Healthcare',
        'country': 'United States'
    }
]

employee_detail_list = [
    {
        'name': 'EMP-0001',
        'first_name': 'John',
        'last_name': 'Doe',
        'full_name': 'John Doe',
        'company': 'Company 1',
        'nationality': 'Australia'
    },
    {
        'name': 'EMP-0002',
        'first_name': 'Tom',
        'last_name': 'Smith',
        'full_name': 'Tom Smith',
        'company': 'Company 2',
        'nationality': 'United States'
    },
    {
        'name': 'EMP-0003',
        'first_name': 'Andrew',
        'last_name': 'Sebastian',
        'full_name': 'Andrew Sebastian',
        'company': 'Company 3',
        'nationality': 'United States'
    },
    {
        'name': 'EMP-0005',
        'first_name': 'Ying Han',
        'last_name': 'Tan',
        'full_name': 'Ying Han Tan',
        'company': 'Company 1',
        'nationality': 'Australia'
    },
    {
        'name': 'EMP-0015',
        'first_name': 'Kenneth',
        'last_name': 'Ng',
        'full_name': 'Kenneth Ng',
        'company': 'Company 3',
        'nationality': 'United States'
    },
    {
        'name': 'EMP-0018',
        'first_name': 'Rubby',
        'last_name': 'Lee',
        'full_name': 'Rubby Lee',
        'company': 'Company 2',
        'nationality': 'Hong Kong'
    },
    {
        'name': 'EMP-0017',
        'first_name': 'Robert',
        'last_name': 'White',
        'full_name': 'Robert White',
        'company': 'Company 1',
        'nationality': 'United Kingdom'
    }
]

def get_employees_with_company_country():
    # Membuat mapping antara nama perusahaan dan negaranya
    company_country_map = {company['name']: company['country'] for company in company_detail_list}
    
    # Membuat daftar karyawan dengan negara perusahaan
    employees_with_country = []
    for employee in employee_detail_list:
        employees_with_country.append({
            'full_name': employee['full_name'],
            'company': employee['company'],
            'country': company_country_map[employee['company']]
        })
    
    return employees_with_country

# Menampilkan hasil
print(get_employees_with_company_country())

[{'full_name': 'John Doe', 'company': 'Company 1', 'country': 'United States'}, {'full_name': 'Tom Smith', 'company': 'Company 2', 'country': 'United Kingdom'}, {'full_name': 'Andrew Sebastian', 'company': 'Company 3', 'country': 'United States'}, {'full_name': 'Ying Han Tan', 'company': 'Company 1', 'country': 'United States'}, {'full_name': 'Kenneth Ng', 'company': 'Company 3', 'country': 'United States'}, {'full_name': 'Rubby Lee', 'company': 'Company 2', 'country': 'United Kingdom'}, {'full_name': 'Robert White', 'company': 'Company 1', 'country': 'United States'}]